package agent

// Plan represents a structured execution plan generated by the Light Model.
type Plan struct {
	IsComplex bool   `json:"is_complex"`
	Reasoning string `json:"reasoning"`
	Steps     []Step `json:"steps"`
}

// Step represents a single action in the Plan.
type Step struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
}

// PlanSchema is the JSON schema string used to force the LLM to return
// a valid JSON representation of the Plan struct.
const PlanSchema = `{
	"type": "object",
	"properties": {
		"is_complex": {
			"type": "boolean",
			"description": "true if the task requires multiple steps, false otherwise"
		},
		"reasoning": {
			"type": "string",
			"description": "brief explanation of why the task is simple or complex"
		},
		"steps": {
			"type": "array",
			"description": "list of steps to execute if the task is complex",
			"items": {
				"type": "object",
				"properties": {
					"id": { "type": "integer" },
					"description": { "type": "string", "description": "detailed description of what needs to be done in this step" }
				},
				"required": ["id", "description"],
				"additionalProperties": false
			}
		}
	},
	"required": ["is_complex", "reasoning", "steps"],
	"additionalProperties": false
}`
